name: Publish NuGet Package

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # 또는 7.0.x 등 사용 중인 버전

      - name: Restore dependencies
        run: dotnet restore Transcritor.sln

      - name: Build project
        run: dotnet build Transcritor.sln --configuration Release --no-restore

      - name: Pack NuGet
        run: dotnet pack Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj --configuration Release --output ./nupkg

      - name: Push to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.NUGET_API_KEY }}
