name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'  # 예: v1.0.0, v1.0.1 등

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # STEP 1: nuget.config 생성 (GitHub 인증 포함)
    - name: Create nuget.config with GitHub credentials
      run: |
        OWNER="${{ github.repository_owner }}"
        TOKEN="${{ secrets.GITHUB_TOKEN }}"

        cat > nuget.config <<EOF
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="github" value="https://nuget.pkg.github.com/${OWNER}/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <github>
      <Username>${OWNER}</Username>
      <ClearTextPassword>${TOKEN}</ClearTextPassword>
    </github>
  </packageSourceCredentials>
</configuration>
EOF

    # STEP 2: Transcriptor 빌드 및 패키지 푸시
    - name: Build Transcriptor
      run: dotnet build ./Transcriptor/Transcriptor.csproj -c Release

    - name: Pack Transcriptor
      run: dotnet pack ./Transcriptor/Transcriptor.csproj -c Release --output ./nupkg

    - name: Push Transcriptor to GitHub Packages
      run: dotnet nuget push ./nupkg/Transcriptor.*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    # STEP 3: Transcriptor.HanguelRomanization 참조 전환
    - name: Remove ProjectReference to Transcriptor
      run: dotnet remove ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj reference ../Transcriptor/Transcriptor.csproj

    - name: Add PackageReference to Transcriptor
      run: dotnet add ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj package Transcriptor --version 1.0.0 --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    # STEP 4: Transcriptor.HanguelRomanization 빌드 및 패키지 푸시
    - name: Build Transcriptor.HanguelRomanization
      run: dotnet build ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj -c Release

    - name: Pack Transcriptor.HanguelRomanization
      run: dotnet pack ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj -c Release --output ./nupkg

    - name: Push Transcriptor.HanguelRomanization to GitHub Packages
      run: dotnet nuget push ./nupkg/Transcriptor.HanguelRomanization.*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
