name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # Remove any checked-in nuget.config that contains bad credentials
    - name: Remove checked-in nuget.config
      run: rm -f ./nuget.config

    # Configure feeds at runtime using secrets (no credentials committed)
    - name: Configure NuGet feeds (nuget.org + GitHub Packages)
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
      run: |
        # Ensure nuget.org is available
        dotnet nuget add source "https://api.nuget.org/v3/index.json" -n nuget.org || true

        # Add GitHub Packages feed and store credentials in the runner config (not committed)
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -n github-packages --username "${{ github.repository_owner }}" --password "$GITHUB_TOKEN" --store-password-in-clear-text || true

    # STEP 1: Transcriptor build / pack / push
    - name: Build Transcriptor
      run: dotnet build ./Transcriptor/Transcriptor.csproj -c Release

    - name: Pack Transcriptor
      run: dotnet pack ./Transcriptor/Transcriptor.csproj -c Release --output ./nupkg

    - name: Push Transcriptor to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget push ./nupkg/Transcriptor.*.nupkg --source "github-packages" --api-key "$GITHUB_TOKEN" --skip-duplicate

    # STEP 2: Switch Transcriptor.HanguelRomanization to use package instead of ProjectReference
    - name: Remove ProjectReference to Transcriptor
      run: dotnet remove ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj reference ../Transcriptor/Transcriptor.csproj

    - name: Add PackageReference to Transcriptor
      run: dotnet add ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj package Transcriptor --version 1.0.0 --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    # STEP 3: Transcriptor.HanguelRomanization build / pack / push
    - name: Build Transcriptor.HanguelRomanization
      run: dotnet build ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj -c Release

    - name: Pack Transcriptor.HanguelRomanization
      run: dotnet pack ./Transcriptor.HanguelRomanization/Transcriptor.HanguelRomanization.csproj -c Release --output ./nupkg

    - name: Push Transcriptor.HanguelRomanization to GitHub Packages
      run: |
        dotnet nuget push ./nupkg/Transcriptor.HanguelRomanization.*.nupkg --source "github-packages" --api-key "$GITHUB_TOKEN" --skip-duplicate
